// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComplexMapMessage.proto

package com.blueapron.connect.protobuf;

public final class ComplexMapMessage {
  private ComplexMapMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComplexMapTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:blueapron.connect.protobuf.ComplexMapType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
     */
    com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId getUserId();
    /**
     * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
     */
    com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserIdOrBuilder getUserIdOrBuilder();

    /**
     * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
     */
    int getUserMessagesCount();
    /**
     * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
     */
    boolean containsUserMessages(
        java.lang.String key);
    /**
     * Use {@link #getUserMessagesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId>
    getUserMessages();
    /**
     * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
     */
    java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId>
    getUserMessagesMap();
    /**
     * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
     */

    com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId getUserMessagesOrDefault(
        java.lang.String key,
        com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId defaultValue);
    /**
     * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
     */

    com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId getUserMessagesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code blueapron.connect.protobuf.ComplexMapType}
   */
  public  static final class ComplexMapType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:blueapron.connect.protobuf.ComplexMapType)
      ComplexMapTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComplexMapType.newBuilder() to construct.
    private ComplexMapType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComplexMapType() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ComplexMapType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId.Builder subBuilder = null;
              if (userId_ != null) {
                subBuilder = userId_.toBuilder();
              }
              userId_ = input.readMessage(com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userId_);
                userId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                userMessages_ = com.google.protobuf.MapField.newMapField(
                    UserMessagesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId>
              userMessages__ = input.readMessage(
                  UserMessagesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              userMessages_.getMutableMap().put(
                  userMessages__.getKey(), userMessages__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blueapron.connect.protobuf.ComplexMapMessage.internal_static_blueapron_connect_protobuf_ComplexMapType_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetUserMessages();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blueapron.connect.protobuf.ComplexMapMessage.internal_static_blueapron_connect_protobuf_ComplexMapType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType.class, com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType.Builder.class);
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId userId_;
    /**
     * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
     */
    public boolean hasUserId() {
      return userId_ != null;
    }
    /**
     * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
     */
    public com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId getUserId() {
      return userId_ == null ? com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId.getDefaultInstance() : userId_;
    }
    /**
     * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
     */
    public com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserIdOrBuilder getUserIdOrBuilder() {
      return getUserId();
    }

    public static final int USER_MESSAGES_FIELD_NUMBER = 2;
    private static final class UserMessagesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId>newDefaultInstance(
                  com.blueapron.connect.protobuf.ComplexMapMessage.internal_static_blueapron_connect_protobuf_ComplexMapType_UserMessagesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> userMessages_;
    private com.google.protobuf.MapField<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId>
    internalGetUserMessages() {
      if (userMessages_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UserMessagesDefaultEntryHolder.defaultEntry);
      }
      return userMessages_;
    }

    public int getUserMessagesCount() {
      return internalGetUserMessages().getMap().size();
    }
    /**
     * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
     */

    public boolean containsUserMessages(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetUserMessages().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUserMessagesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> getUserMessages() {
      return getUserMessagesMap();
    }
    /**
     * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
     */

    public java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> getUserMessagesMap() {
      return internalGetUserMessages().getMap();
    }
    /**
     * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
     */

    public com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId getUserMessagesOrDefault(
        java.lang.String key,
        com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> map =
          internalGetUserMessages().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
     */

    public com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId getUserMessagesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> map =
          internalGetUserMessages().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != null) {
        output.writeMessage(1, getUserId());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetUserMessages(),
          UserMessagesDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUserId());
      }
      for (java.util.Map.Entry<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> entry
           : internalGetUserMessages().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId>
        userMessages__ = UserMessagesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, userMessages__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType)) {
        return super.equals(obj);
      }
      com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType other = (com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType) obj;

      if (hasUserId() != other.hasUserId()) return false;
      if (hasUserId()) {
        if (!getUserId()
            .equals(other.getUserId())) return false;
      }
      if (!internalGetUserMessages().equals(
          other.internalGetUserMessages())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUserId()) {
        hash = (37 * hash) + USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId().hashCode();
      }
      if (!internalGetUserMessages().getMap().isEmpty()) {
        hash = (37 * hash) + USER_MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetUserMessages().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code blueapron.connect.protobuf.ComplexMapType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:blueapron.connect.protobuf.ComplexMapType)
        com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blueapron.connect.protobuf.ComplexMapMessage.internal_static_blueapron_connect_protobuf_ComplexMapType_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetUserMessages();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableUserMessages();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blueapron.connect.protobuf.ComplexMapMessage.internal_static_blueapron_connect_protobuf_ComplexMapType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType.class, com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType.Builder.class);
      }

      // Construct using com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userIdBuilder_ == null) {
          userId_ = null;
        } else {
          userId_ = null;
          userIdBuilder_ = null;
        }
        internalGetMutableUserMessages().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blueapron.connect.protobuf.ComplexMapMessage.internal_static_blueapron_connect_protobuf_ComplexMapType_descriptor;
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType getDefaultInstanceForType() {
        return com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType.getDefaultInstance();
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType build() {
        com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType buildPartial() {
        com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType result = new com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (userIdBuilder_ == null) {
          result.userId_ = userId_;
        } else {
          result.userId_ = userIdBuilder_.build();
        }
        result.userMessages_ = internalGetUserMessages();
        result.userMessages_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType) {
          return mergeFrom((com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType other) {
        if (other == com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          mergeUserId(other.getUserId());
        }
        internalGetMutableUserMessages().mergeFrom(
            other.internalGetUserMessages());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId userId_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId.Builder, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserIdOrBuilder> userIdBuilder_;
      /**
       * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
       */
      public boolean hasUserId() {
        return userIdBuilder_ != null || userId_ != null;
      }
      /**
       * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
       */
      public com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId getUserId() {
        if (userIdBuilder_ == null) {
          return userId_ == null ? com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId.getDefaultInstance() : userId_;
        } else {
          return userIdBuilder_.getMessage();
        }
      }
      /**
       * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
       */
      public Builder setUserId(com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId value) {
        if (userIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userId_ = value;
          onChanged();
        } else {
          userIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
       */
      public Builder setUserId(
          com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId.Builder builderForValue) {
        if (userIdBuilder_ == null) {
          userId_ = builderForValue.build();
          onChanged();
        } else {
          userIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
       */
      public Builder mergeUserId(com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId value) {
        if (userIdBuilder_ == null) {
          if (userId_ != null) {
            userId_ =
              com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId.newBuilder(userId_).mergeFrom(value).buildPartial();
          } else {
            userId_ = value;
          }
          onChanged();
        } else {
          userIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
       */
      public Builder clearUserId() {
        if (userIdBuilder_ == null) {
          userId_ = null;
          onChanged();
        } else {
          userId_ = null;
          userIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
       */
      public com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId.Builder getUserIdBuilder() {
        
        onChanged();
        return getUserIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
       */
      public com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserIdOrBuilder getUserIdOrBuilder() {
        if (userIdBuilder_ != null) {
          return userIdBuilder_.getMessageOrBuilder();
        } else {
          return userId_ == null ?
              com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId.getDefaultInstance() : userId_;
        }
      }
      /**
       * <code>.blueapron.connect.protobuf.UserId user_id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId.Builder, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserIdOrBuilder> 
          getUserIdFieldBuilder() {
        if (userIdBuilder_ == null) {
          userIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserId.Builder, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.UserIdOrBuilder>(
                  getUserId(),
                  getParentForChildren(),
                  isClean());
          userId_ = null;
        }
        return userIdBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> userMessages_;
      private com.google.protobuf.MapField<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId>
      internalGetUserMessages() {
        if (userMessages_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              UserMessagesDefaultEntryHolder.defaultEntry);
        }
        return userMessages_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId>
      internalGetMutableUserMessages() {
        onChanged();;
        if (userMessages_ == null) {
          userMessages_ = com.google.protobuf.MapField.newMapField(
              UserMessagesDefaultEntryHolder.defaultEntry);
        }
        if (!userMessages_.isMutable()) {
          userMessages_ = userMessages_.copy();
        }
        return userMessages_;
      }

      public int getUserMessagesCount() {
        return internalGetUserMessages().getMap().size();
      }
      /**
       * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
       */

      public boolean containsUserMessages(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetUserMessages().getMap().containsKey(key);
      }
      /**
       * Use {@link #getUserMessagesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> getUserMessages() {
        return getUserMessagesMap();
      }
      /**
       * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
       */

      public java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> getUserMessagesMap() {
        return internalGetUserMessages().getMap();
      }
      /**
       * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
       */

      public com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId getUserMessagesOrDefault(
          java.lang.String key,
          com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> map =
            internalGetUserMessages().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
       */

      public com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId getUserMessagesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> map =
            internalGetUserMessages().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearUserMessages() {
        internalGetMutableUserMessages().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
       */

      public Builder removeUserMessages(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableUserMessages().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId>
      getMutableUserMessages() {
        return internalGetMutableUserMessages().getMutableMap();
      }
      /**
       * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
       */
      public Builder putUserMessages(
          java.lang.String key,
          com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableUserMessages().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .blueapron.connect.protobuf.MessageId&gt; user_messages = 2;</code>
       */

      public Builder putAllUserMessages(
          java.util.Map<java.lang.String, com.blueapron.connect.protobuf.NestedTestProtoOuterClass.MessageId> values) {
        internalGetMutableUserMessages().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:blueapron.connect.protobuf.ComplexMapType)
    }

    // @@protoc_insertion_point(class_scope:blueapron.connect.protobuf.ComplexMapType)
    private static final com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType();
    }

    public static com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComplexMapType>
        PARSER = new com.google.protobuf.AbstractParser<ComplexMapType>() {
      @java.lang.Override
      public ComplexMapType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ComplexMapType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ComplexMapType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComplexMapType> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.blueapron.connect.protobuf.ComplexMapMessage.ComplexMapType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blueapron_connect_protobuf_ComplexMapType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blueapron_connect_protobuf_ComplexMapType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blueapron_connect_protobuf_ComplexMapType_UserMessagesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blueapron_connect_protobuf_ComplexMapType_UserMessagesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ComplexMapMessage.proto\022\032blueapron.con" +
      "nect.protobuf\032\025NestedTestProto.proto\"\366\001\n" +
      "\016ComplexMapType\0223\n\007user_id\030\001 \001(\0132\".bluea" +
      "pron.connect.protobuf.UserId\022S\n\ruser_mes" +
      "sages\030\002 \003(\0132<.blueapron.connect.protobuf" +
      ".ComplexMapType.UserMessagesEntry\032Z\n\021Use" +
      "rMessagesEntry\022\013\n\003key\030\001 \001(\t\0224\n\005value\030\002 \001" +
      "(\0132%.blueapron.connect.protobuf.MessageI" +
      "d:\0028\001B \n\036com.blueapron.connect.protobufb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.blueapron.connect.protobuf.NestedTestProtoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_blueapron_connect_protobuf_ComplexMapType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_blueapron_connect_protobuf_ComplexMapType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blueapron_connect_protobuf_ComplexMapType_descriptor,
        new java.lang.String[] { "UserId", "UserMessages", });
    internal_static_blueapron_connect_protobuf_ComplexMapType_UserMessagesEntry_descriptor =
      internal_static_blueapron_connect_protobuf_ComplexMapType_descriptor.getNestedTypes().get(0);
    internal_static_blueapron_connect_protobuf_ComplexMapType_UserMessagesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blueapron_connect_protobuf_ComplexMapType_UserMessagesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.blueapron.connect.protobuf.NestedTestProtoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
