// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafka_message.proto

package com.blueapron.connect.protobuf;

public final class KafkaMessageOuterClass {
  private KafkaMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_blueapron_connect_protobuf_KafkaMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_blueapron_connect_protobuf_KafkaMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023kafka_message.proto\022\032blueapron.connect" +
      ".protobuf\"C\n\014KafkaMessage\022\014\n\004uuid\030\001 \001(\t\022" +
      "\024\n\014enqueue_time\030\002 \001(\003\022\017\n\007message\030\003 \001(\014B\"" +
      "\n\036com.blueapron.connect.protobufP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_blueapron_connect_protobuf_KafkaMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_blueapron_connect_protobuf_KafkaMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_blueapron_connect_protobuf_KafkaMessage_descriptor,
        new java.lang.String[] { "Uuid", "EnqueueTime", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
