// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafka_message.proto

package com.blueapron.connect.protobuf;

public interface KafkaMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blueapron.connect.protobuf.KafkaMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unique id for this message
   * </pre>
   *
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <pre>
   * unique id for this message
   * </pre>
   *
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <pre>
   * time this message was enqueued
   * </pre>
   *
   * <code>int64 enqueue_time = 2;</code>
   * @return The enqueueTime.
   */
  long getEnqueueTime();

  /**
   * <pre>
   * actual payload
   * </pre>
   *
   * <code>bytes message = 3;</code>
   * @return The message.
   */
  com.google.protobuf.ByteString getMessage();
}
