// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MapValue.proto

package com.blueapron.connect.protobuf;

public final class MapValueOuterClass {
  private MapValueOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MapValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MapValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int32, float&gt; value = 1;</code>
     */
    int getValueCount();
    /**
     * <code>map&lt;int32, float&gt; value = 1;</code>
     */
    boolean containsValue(
        int key);
    /**
     * Use {@link #getValueMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Float>
    getValue();
    /**
     * <code>map&lt;int32, float&gt; value = 1;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Float>
    getValueMap();
    /**
     * <code>map&lt;int32, float&gt; value = 1;</code>
     */

    float getValueOrDefault(
        int key,
        float defaultValue);
    /**
     * <code>map&lt;int32, float&gt; value = 1;</code>
     */

    float getValueOrThrow(
        int key);
  }
  /**
   * <pre>
   * Wrapper message for `Map`.
   * </pre>
   *
   * Protobuf type {@code MapValue}
   */
  public  static final class MapValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MapValue)
      MapValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MapValue.newBuilder() to construct.
    private MapValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MapValue() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MapValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                value_ = com.google.protobuf.MapField.newMapField(
                    ValueDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Float>
              value__ = input.readMessage(
                  ValueDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              value_.getMutableMap().put(
                  value__.getKey(), value__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blueapron.connect.protobuf.MapValueOuterClass.internal_static_MapValue_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetValue();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blueapron.connect.protobuf.MapValueOuterClass.internal_static_MapValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blueapron.connect.protobuf.MapValueOuterClass.MapValue.class, com.blueapron.connect.protobuf.MapValueOuterClass.MapValue.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private static final class ValueDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Float> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Float>newDefaultInstance(
                  com.blueapron.connect.protobuf.MapValueOuterClass.internal_static_MapValue_ValueEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.FLOAT,
                  0F);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Float> value_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Float>
    internalGetValue() {
      if (value_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValueDefaultEntryHolder.defaultEntry);
      }
      return value_;
    }

    public int getValueCount() {
      return internalGetValue().getMap().size();
    }
    /**
     * <code>map&lt;int32, float&gt; value = 1;</code>
     */

    public boolean containsValue(
        int key) {
      
      return internalGetValue().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValueMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Float> getValue() {
      return getValueMap();
    }
    /**
     * <code>map&lt;int32, float&gt; value = 1;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Float> getValueMap() {
      return internalGetValue().getMap();
    }
    /**
     * <code>map&lt;int32, float&gt; value = 1;</code>
     */

    public float getValueOrDefault(
        int key,
        float defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Float> map =
          internalGetValue().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, float&gt; value = 1;</code>
     */

    public float getValueOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Float> map =
          internalGetValue().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetValue(),
          ValueDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Float> entry
           : internalGetValue().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Float>
        value__ = ValueDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, value__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.blueapron.connect.protobuf.MapValueOuterClass.MapValue)) {
        return super.equals(obj);
      }
      com.blueapron.connect.protobuf.MapValueOuterClass.MapValue other = (com.blueapron.connect.protobuf.MapValueOuterClass.MapValue) obj;

      boolean result = true;
      result = result && internalGetValue().equals(
          other.internalGetValue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetValue().getMap().isEmpty()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blueapron.connect.protobuf.MapValueOuterClass.MapValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Wrapper message for `Map`.
     * </pre>
     *
     * Protobuf type {@code MapValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MapValue)
        com.blueapron.connect.protobuf.MapValueOuterClass.MapValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blueapron.connect.protobuf.MapValueOuterClass.internal_static_MapValue_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetValue();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableValue();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blueapron.connect.protobuf.MapValueOuterClass.internal_static_MapValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blueapron.connect.protobuf.MapValueOuterClass.MapValue.class, com.blueapron.connect.protobuf.MapValueOuterClass.MapValue.Builder.class);
      }

      // Construct using com.blueapron.connect.protobuf.MapValueOuterClass.MapValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableValue().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blueapron.connect.protobuf.MapValueOuterClass.internal_static_MapValue_descriptor;
      }

      public com.blueapron.connect.protobuf.MapValueOuterClass.MapValue getDefaultInstanceForType() {
        return com.blueapron.connect.protobuf.MapValueOuterClass.MapValue.getDefaultInstance();
      }

      public com.blueapron.connect.protobuf.MapValueOuterClass.MapValue build() {
        com.blueapron.connect.protobuf.MapValueOuterClass.MapValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blueapron.connect.protobuf.MapValueOuterClass.MapValue buildPartial() {
        com.blueapron.connect.protobuf.MapValueOuterClass.MapValue result = new com.blueapron.connect.protobuf.MapValueOuterClass.MapValue(this);
        int from_bitField0_ = bitField0_;
        result.value_ = internalGetValue();
        result.value_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blueapron.connect.protobuf.MapValueOuterClass.MapValue) {
          return mergeFrom((com.blueapron.connect.protobuf.MapValueOuterClass.MapValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blueapron.connect.protobuf.MapValueOuterClass.MapValue other) {
        if (other == com.blueapron.connect.protobuf.MapValueOuterClass.MapValue.getDefaultInstance()) return this;
        internalGetMutableValue().mergeFrom(
            other.internalGetValue());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blueapron.connect.protobuf.MapValueOuterClass.MapValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blueapron.connect.protobuf.MapValueOuterClass.MapValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Float> value_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Float>
      internalGetValue() {
        if (value_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValueDefaultEntryHolder.defaultEntry);
        }
        return value_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Float>
      internalGetMutableValue() {
        onChanged();;
        if (value_ == null) {
          value_ = com.google.protobuf.MapField.newMapField(
              ValueDefaultEntryHolder.defaultEntry);
        }
        if (!value_.isMutable()) {
          value_ = value_.copy();
        }
        return value_;
      }

      public int getValueCount() {
        return internalGetValue().getMap().size();
      }
      /**
       * <code>map&lt;int32, float&gt; value = 1;</code>
       */

      public boolean containsValue(
          int key) {
        
        return internalGetValue().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValueMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Float> getValue() {
        return getValueMap();
      }
      /**
       * <code>map&lt;int32, float&gt; value = 1;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.Float> getValueMap() {
        return internalGetValue().getMap();
      }
      /**
       * <code>map&lt;int32, float&gt; value = 1;</code>
       */

      public float getValueOrDefault(
          int key,
          float defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.Float> map =
            internalGetValue().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, float&gt; value = 1;</code>
       */

      public float getValueOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.Float> map =
            internalGetValue().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearValue() {
        internalGetMutableValue().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, float&gt; value = 1;</code>
       */

      public Builder removeValue(
          int key) {
        
        internalGetMutableValue().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Float>
      getMutableValue() {
        return internalGetMutableValue().getMutableMap();
      }
      /**
       * <code>map&lt;int32, float&gt; value = 1;</code>
       */
      public Builder putValue(
          int key,
          float value) {
        
        
        internalGetMutableValue().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, float&gt; value = 1;</code>
       */

      public Builder putAllValue(
          java.util.Map<java.lang.Integer, java.lang.Float> values) {
        internalGetMutableValue().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MapValue)
    }

    // @@protoc_insertion_point(class_scope:MapValue)
    private static final com.blueapron.connect.protobuf.MapValueOuterClass.MapValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blueapron.connect.protobuf.MapValueOuterClass.MapValue();
    }

    public static com.blueapron.connect.protobuf.MapValueOuterClass.MapValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MapValue>
        PARSER = new com.google.protobuf.AbstractParser<MapValue>() {
      public MapValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MapValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MapValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MapValue> getParserForType() {
      return PARSER;
    }

    public com.blueapron.connect.protobuf.MapValueOuterClass.MapValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MapValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MapValue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MapValue_ValueEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MapValue_ValueEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MapValue.proto\"]\n\010MapValue\022#\n\005value\030\001 " +
      "\003(\0132\024.MapValue.ValueEntry\032,\n\nValueEntry\022" +
      "\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\002:\0028\001B \n\036com.b" +
      "lueapron.connect.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MapValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MapValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MapValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_MapValue_ValueEntry_descriptor =
      internal_static_MapValue_descriptor.getNestedTypes().get(0);
    internal_static_MapValue_ValueEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MapValue_ValueEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
