// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OneOfStructs.proto

package com.blueapron.connect.protobuf;

public final class OneOfStructs {
  private OneOfStructs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FirstOrBuilder extends
      // @@protoc_insertion_point(interface_extends:First)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code First}
   */
  public  static final class First extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:First)
      FirstOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use First.newBuilder() to construct.
    private First(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private First() {
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private First(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blueapron.connect.protobuf.OneOfStructs.internal_static_First_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blueapron.connect.protobuf.OneOfStructs.internal_static_First_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blueapron.connect.protobuf.OneOfStructs.First.class, com.blueapron.connect.protobuf.OneOfStructs.First.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 1;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.blueapron.connect.protobuf.OneOfStructs.First)) {
        return super.equals(obj);
      }
      com.blueapron.connect.protobuf.OneOfStructs.First other = (com.blueapron.connect.protobuf.OneOfStructs.First) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.blueapron.connect.protobuf.OneOfStructs.First parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.First parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.First parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.First parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.First parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.First parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.First parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.First parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.First parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.First parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.First parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.First parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blueapron.connect.protobuf.OneOfStructs.First prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code First}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:First)
        com.blueapron.connect.protobuf.OneOfStructs.FirstOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blueapron.connect.protobuf.OneOfStructs.internal_static_First_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blueapron.connect.protobuf.OneOfStructs.internal_static_First_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blueapron.connect.protobuf.OneOfStructs.First.class, com.blueapron.connect.protobuf.OneOfStructs.First.Builder.class);
      }

      // Construct using com.blueapron.connect.protobuf.OneOfStructs.First.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blueapron.connect.protobuf.OneOfStructs.internal_static_First_descriptor;
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.OneOfStructs.First getDefaultInstanceForType() {
        return com.blueapron.connect.protobuf.OneOfStructs.First.getDefaultInstance();
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.OneOfStructs.First build() {
        com.blueapron.connect.protobuf.OneOfStructs.First result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.OneOfStructs.First buildPartial() {
        com.blueapron.connect.protobuf.OneOfStructs.First result = new com.blueapron.connect.protobuf.OneOfStructs.First(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blueapron.connect.protobuf.OneOfStructs.First) {
          return mergeFrom((com.blueapron.connect.protobuf.OneOfStructs.First)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blueapron.connect.protobuf.OneOfStructs.First other) {
        if (other == com.blueapron.connect.protobuf.OneOfStructs.First.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blueapron.connect.protobuf.OneOfStructs.First parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blueapron.connect.protobuf.OneOfStructs.First) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:First)
    }

    // @@protoc_insertion_point(class_scope:First)
    private static final com.blueapron.connect.protobuf.OneOfStructs.First DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blueapron.connect.protobuf.OneOfStructs.First();
    }

    public static com.blueapron.connect.protobuf.OneOfStructs.First getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<First>
        PARSER = new com.google.protobuf.AbstractParser<First>() {
      @java.lang.Override
      public First parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new First(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<First> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<First> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.blueapron.connect.protobuf.OneOfStructs.First getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SecondOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Second)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code Second}
   */
  public  static final class Second extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Second)
      SecondOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Second.newBuilder() to construct.
    private Second(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Second() {
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Second(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blueapron.connect.protobuf.OneOfStructs.internal_static_Second_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blueapron.connect.protobuf.OneOfStructs.internal_static_Second_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blueapron.connect.protobuf.OneOfStructs.Second.class, com.blueapron.connect.protobuf.OneOfStructs.Second.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.blueapron.connect.protobuf.OneOfStructs.Second)) {
        return super.equals(obj);
      }
      com.blueapron.connect.protobuf.OneOfStructs.Second other = (com.blueapron.connect.protobuf.OneOfStructs.Second) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.Second parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blueapron.connect.protobuf.OneOfStructs.Second prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Second}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Second)
        com.blueapron.connect.protobuf.OneOfStructs.SecondOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blueapron.connect.protobuf.OneOfStructs.internal_static_Second_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blueapron.connect.protobuf.OneOfStructs.internal_static_Second_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blueapron.connect.protobuf.OneOfStructs.Second.class, com.blueapron.connect.protobuf.OneOfStructs.Second.Builder.class);
      }

      // Construct using com.blueapron.connect.protobuf.OneOfStructs.Second.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blueapron.connect.protobuf.OneOfStructs.internal_static_Second_descriptor;
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.OneOfStructs.Second getDefaultInstanceForType() {
        return com.blueapron.connect.protobuf.OneOfStructs.Second.getDefaultInstance();
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.OneOfStructs.Second build() {
        com.blueapron.connect.protobuf.OneOfStructs.Second result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.OneOfStructs.Second buildPartial() {
        com.blueapron.connect.protobuf.OneOfStructs.Second result = new com.blueapron.connect.protobuf.OneOfStructs.Second(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blueapron.connect.protobuf.OneOfStructs.Second) {
          return mergeFrom((com.blueapron.connect.protobuf.OneOfStructs.Second)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blueapron.connect.protobuf.OneOfStructs.Second other) {
        if (other == com.blueapron.connect.protobuf.OneOfStructs.Second.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blueapron.connect.protobuf.OneOfStructs.Second parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blueapron.connect.protobuf.OneOfStructs.Second) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Second)
    }

    // @@protoc_insertion_point(class_scope:Second)
    private static final com.blueapron.connect.protobuf.OneOfStructs.Second DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blueapron.connect.protobuf.OneOfStructs.Second();
    }

    public static com.blueapron.connect.protobuf.OneOfStructs.Second getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Second>
        PARSER = new com.google.protobuf.AbstractParser<Second>() {
      @java.lang.Override
      public Second parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Second(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Second> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Second> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.blueapron.connect.protobuf.OneOfStructs.Second getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OneOfContainerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OneOfContainer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.First first = 1;</code>
     */
    boolean hasFirst();
    /**
     * <code>.First first = 1;</code>
     */
    com.blueapron.connect.protobuf.OneOfStructs.First getFirst();
    /**
     * <code>.First first = 1;</code>
     */
    com.blueapron.connect.protobuf.OneOfStructs.FirstOrBuilder getFirstOrBuilder();

    /**
     * <code>.Second second = 2;</code>
     */
    boolean hasSecond();
    /**
     * <code>.Second second = 2;</code>
     */
    com.blueapron.connect.protobuf.OneOfStructs.Second getSecond();
    /**
     * <code>.Second second = 2;</code>
     */
    com.blueapron.connect.protobuf.OneOfStructs.SecondOrBuilder getSecondOrBuilder();

    public com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer.PossibilitiesCase getPossibilitiesCase();
  }
  /**
   * Protobuf type {@code OneOfContainer}
   */
  public  static final class OneOfContainer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OneOfContainer)
      OneOfContainerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OneOfContainer.newBuilder() to construct.
    private OneOfContainer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OneOfContainer() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OneOfContainer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.blueapron.connect.protobuf.OneOfStructs.First.Builder subBuilder = null;
              if (possibilitiesCase_ == 1) {
                subBuilder = ((com.blueapron.connect.protobuf.OneOfStructs.First) possibilities_).toBuilder();
              }
              possibilities_ =
                  input.readMessage(com.blueapron.connect.protobuf.OneOfStructs.First.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.blueapron.connect.protobuf.OneOfStructs.First) possibilities_);
                possibilities_ = subBuilder.buildPartial();
              }
              possibilitiesCase_ = 1;
              break;
            }
            case 18: {
              com.blueapron.connect.protobuf.OneOfStructs.Second.Builder subBuilder = null;
              if (possibilitiesCase_ == 2) {
                subBuilder = ((com.blueapron.connect.protobuf.OneOfStructs.Second) possibilities_).toBuilder();
              }
              possibilities_ =
                  input.readMessage(com.blueapron.connect.protobuf.OneOfStructs.Second.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.blueapron.connect.protobuf.OneOfStructs.Second) possibilities_);
                possibilities_ = subBuilder.buildPartial();
              }
              possibilitiesCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blueapron.connect.protobuf.OneOfStructs.internal_static_OneOfContainer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blueapron.connect.protobuf.OneOfStructs.internal_static_OneOfContainer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer.class, com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer.Builder.class);
    }

    private int possibilitiesCase_ = 0;
    private java.lang.Object possibilities_;
    public enum PossibilitiesCase
        implements com.google.protobuf.Internal.EnumLite {
      FIRST(1),
      SECOND(2),
      POSSIBILITIES_NOT_SET(0);
      private final int value;
      private PossibilitiesCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PossibilitiesCase valueOf(int value) {
        return forNumber(value);
      }

      public static PossibilitiesCase forNumber(int value) {
        switch (value) {
          case 1: return FIRST;
          case 2: return SECOND;
          case 0: return POSSIBILITIES_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PossibilitiesCase
    getPossibilitiesCase() {
      return PossibilitiesCase.forNumber(
          possibilitiesCase_);
    }

    public static final int FIRST_FIELD_NUMBER = 1;
    /**
     * <code>.First first = 1;</code>
     */
    public boolean hasFirst() {
      return possibilitiesCase_ == 1;
    }
    /**
     * <code>.First first = 1;</code>
     */
    public com.blueapron.connect.protobuf.OneOfStructs.First getFirst() {
      if (possibilitiesCase_ == 1) {
         return (com.blueapron.connect.protobuf.OneOfStructs.First) possibilities_;
      }
      return com.blueapron.connect.protobuf.OneOfStructs.First.getDefaultInstance();
    }
    /**
     * <code>.First first = 1;</code>
     */
    public com.blueapron.connect.protobuf.OneOfStructs.FirstOrBuilder getFirstOrBuilder() {
      if (possibilitiesCase_ == 1) {
         return (com.blueapron.connect.protobuf.OneOfStructs.First) possibilities_;
      }
      return com.blueapron.connect.protobuf.OneOfStructs.First.getDefaultInstance();
    }

    public static final int SECOND_FIELD_NUMBER = 2;
    /**
     * <code>.Second second = 2;</code>
     */
    public boolean hasSecond() {
      return possibilitiesCase_ == 2;
    }
    /**
     * <code>.Second second = 2;</code>
     */
    public com.blueapron.connect.protobuf.OneOfStructs.Second getSecond() {
      if (possibilitiesCase_ == 2) {
         return (com.blueapron.connect.protobuf.OneOfStructs.Second) possibilities_;
      }
      return com.blueapron.connect.protobuf.OneOfStructs.Second.getDefaultInstance();
    }
    /**
     * <code>.Second second = 2;</code>
     */
    public com.blueapron.connect.protobuf.OneOfStructs.SecondOrBuilder getSecondOrBuilder() {
      if (possibilitiesCase_ == 2) {
         return (com.blueapron.connect.protobuf.OneOfStructs.Second) possibilities_;
      }
      return com.blueapron.connect.protobuf.OneOfStructs.Second.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (possibilitiesCase_ == 1) {
        output.writeMessage(1, (com.blueapron.connect.protobuf.OneOfStructs.First) possibilities_);
      }
      if (possibilitiesCase_ == 2) {
        output.writeMessage(2, (com.blueapron.connect.protobuf.OneOfStructs.Second) possibilities_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (possibilitiesCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.blueapron.connect.protobuf.OneOfStructs.First) possibilities_);
      }
      if (possibilitiesCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.blueapron.connect.protobuf.OneOfStructs.Second) possibilities_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer)) {
        return super.equals(obj);
      }
      com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer other = (com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer) obj;

      if (!getPossibilitiesCase().equals(other.getPossibilitiesCase())) return false;
      switch (possibilitiesCase_) {
        case 1:
          if (!getFirst()
              .equals(other.getFirst())) return false;
          break;
        case 2:
          if (!getSecond()
              .equals(other.getSecond())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (possibilitiesCase_) {
        case 1:
          hash = (37 * hash) + FIRST_FIELD_NUMBER;
          hash = (53 * hash) + getFirst().hashCode();
          break;
        case 2:
          hash = (37 * hash) + SECOND_FIELD_NUMBER;
          hash = (53 * hash) + getSecond().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OneOfContainer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OneOfContainer)
        com.blueapron.connect.protobuf.OneOfStructs.OneOfContainerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blueapron.connect.protobuf.OneOfStructs.internal_static_OneOfContainer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blueapron.connect.protobuf.OneOfStructs.internal_static_OneOfContainer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer.class, com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer.Builder.class);
      }

      // Construct using com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        possibilitiesCase_ = 0;
        possibilities_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blueapron.connect.protobuf.OneOfStructs.internal_static_OneOfContainer_descriptor;
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer getDefaultInstanceForType() {
        return com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer.getDefaultInstance();
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer build() {
        com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer buildPartial() {
        com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer result = new com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer(this);
        if (possibilitiesCase_ == 1) {
          if (firstBuilder_ == null) {
            result.possibilities_ = possibilities_;
          } else {
            result.possibilities_ = firstBuilder_.build();
          }
        }
        if (possibilitiesCase_ == 2) {
          if (secondBuilder_ == null) {
            result.possibilities_ = possibilities_;
          } else {
            result.possibilities_ = secondBuilder_.build();
          }
        }
        result.possibilitiesCase_ = possibilitiesCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer) {
          return mergeFrom((com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer other) {
        if (other == com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer.getDefaultInstance()) return this;
        switch (other.getPossibilitiesCase()) {
          case FIRST: {
            mergeFirst(other.getFirst());
            break;
          }
          case SECOND: {
            mergeSecond(other.getSecond());
            break;
          }
          case POSSIBILITIES_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int possibilitiesCase_ = 0;
      private java.lang.Object possibilities_;
      public PossibilitiesCase
          getPossibilitiesCase() {
        return PossibilitiesCase.forNumber(
            possibilitiesCase_);
      }

      public Builder clearPossibilities() {
        possibilitiesCase_ = 0;
        possibilities_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.blueapron.connect.protobuf.OneOfStructs.First, com.blueapron.connect.protobuf.OneOfStructs.First.Builder, com.blueapron.connect.protobuf.OneOfStructs.FirstOrBuilder> firstBuilder_;
      /**
       * <code>.First first = 1;</code>
       */
      public boolean hasFirst() {
        return possibilitiesCase_ == 1;
      }
      /**
       * <code>.First first = 1;</code>
       */
      public com.blueapron.connect.protobuf.OneOfStructs.First getFirst() {
        if (firstBuilder_ == null) {
          if (possibilitiesCase_ == 1) {
            return (com.blueapron.connect.protobuf.OneOfStructs.First) possibilities_;
          }
          return com.blueapron.connect.protobuf.OneOfStructs.First.getDefaultInstance();
        } else {
          if (possibilitiesCase_ == 1) {
            return firstBuilder_.getMessage();
          }
          return com.blueapron.connect.protobuf.OneOfStructs.First.getDefaultInstance();
        }
      }
      /**
       * <code>.First first = 1;</code>
       */
      public Builder setFirst(com.blueapron.connect.protobuf.OneOfStructs.First value) {
        if (firstBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          possibilities_ = value;
          onChanged();
        } else {
          firstBuilder_.setMessage(value);
        }
        possibilitiesCase_ = 1;
        return this;
      }
      /**
       * <code>.First first = 1;</code>
       */
      public Builder setFirst(
          com.blueapron.connect.protobuf.OneOfStructs.First.Builder builderForValue) {
        if (firstBuilder_ == null) {
          possibilities_ = builderForValue.build();
          onChanged();
        } else {
          firstBuilder_.setMessage(builderForValue.build());
        }
        possibilitiesCase_ = 1;
        return this;
      }
      /**
       * <code>.First first = 1;</code>
       */
      public Builder mergeFirst(com.blueapron.connect.protobuf.OneOfStructs.First value) {
        if (firstBuilder_ == null) {
          if (possibilitiesCase_ == 1 &&
              possibilities_ != com.blueapron.connect.protobuf.OneOfStructs.First.getDefaultInstance()) {
            possibilities_ = com.blueapron.connect.protobuf.OneOfStructs.First.newBuilder((com.blueapron.connect.protobuf.OneOfStructs.First) possibilities_)
                .mergeFrom(value).buildPartial();
          } else {
            possibilities_ = value;
          }
          onChanged();
        } else {
          if (possibilitiesCase_ == 1) {
            firstBuilder_.mergeFrom(value);
          }
          firstBuilder_.setMessage(value);
        }
        possibilitiesCase_ = 1;
        return this;
      }
      /**
       * <code>.First first = 1;</code>
       */
      public Builder clearFirst() {
        if (firstBuilder_ == null) {
          if (possibilitiesCase_ == 1) {
            possibilitiesCase_ = 0;
            possibilities_ = null;
            onChanged();
          }
        } else {
          if (possibilitiesCase_ == 1) {
            possibilitiesCase_ = 0;
            possibilities_ = null;
          }
          firstBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.First first = 1;</code>
       */
      public com.blueapron.connect.protobuf.OneOfStructs.First.Builder getFirstBuilder() {
        return getFirstFieldBuilder().getBuilder();
      }
      /**
       * <code>.First first = 1;</code>
       */
      public com.blueapron.connect.protobuf.OneOfStructs.FirstOrBuilder getFirstOrBuilder() {
        if ((possibilitiesCase_ == 1) && (firstBuilder_ != null)) {
          return firstBuilder_.getMessageOrBuilder();
        } else {
          if (possibilitiesCase_ == 1) {
            return (com.blueapron.connect.protobuf.OneOfStructs.First) possibilities_;
          }
          return com.blueapron.connect.protobuf.OneOfStructs.First.getDefaultInstance();
        }
      }
      /**
       * <code>.First first = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.blueapron.connect.protobuf.OneOfStructs.First, com.blueapron.connect.protobuf.OneOfStructs.First.Builder, com.blueapron.connect.protobuf.OneOfStructs.FirstOrBuilder> 
          getFirstFieldBuilder() {
        if (firstBuilder_ == null) {
          if (!(possibilitiesCase_ == 1)) {
            possibilities_ = com.blueapron.connect.protobuf.OneOfStructs.First.getDefaultInstance();
          }
          firstBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.blueapron.connect.protobuf.OneOfStructs.First, com.blueapron.connect.protobuf.OneOfStructs.First.Builder, com.blueapron.connect.protobuf.OneOfStructs.FirstOrBuilder>(
                  (com.blueapron.connect.protobuf.OneOfStructs.First) possibilities_,
                  getParentForChildren(),
                  isClean());
          possibilities_ = null;
        }
        possibilitiesCase_ = 1;
        onChanged();;
        return firstBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.blueapron.connect.protobuf.OneOfStructs.Second, com.blueapron.connect.protobuf.OneOfStructs.Second.Builder, com.blueapron.connect.protobuf.OneOfStructs.SecondOrBuilder> secondBuilder_;
      /**
       * <code>.Second second = 2;</code>
       */
      public boolean hasSecond() {
        return possibilitiesCase_ == 2;
      }
      /**
       * <code>.Second second = 2;</code>
       */
      public com.blueapron.connect.protobuf.OneOfStructs.Second getSecond() {
        if (secondBuilder_ == null) {
          if (possibilitiesCase_ == 2) {
            return (com.blueapron.connect.protobuf.OneOfStructs.Second) possibilities_;
          }
          return com.blueapron.connect.protobuf.OneOfStructs.Second.getDefaultInstance();
        } else {
          if (possibilitiesCase_ == 2) {
            return secondBuilder_.getMessage();
          }
          return com.blueapron.connect.protobuf.OneOfStructs.Second.getDefaultInstance();
        }
      }
      /**
       * <code>.Second second = 2;</code>
       */
      public Builder setSecond(com.blueapron.connect.protobuf.OneOfStructs.Second value) {
        if (secondBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          possibilities_ = value;
          onChanged();
        } else {
          secondBuilder_.setMessage(value);
        }
        possibilitiesCase_ = 2;
        return this;
      }
      /**
       * <code>.Second second = 2;</code>
       */
      public Builder setSecond(
          com.blueapron.connect.protobuf.OneOfStructs.Second.Builder builderForValue) {
        if (secondBuilder_ == null) {
          possibilities_ = builderForValue.build();
          onChanged();
        } else {
          secondBuilder_.setMessage(builderForValue.build());
        }
        possibilitiesCase_ = 2;
        return this;
      }
      /**
       * <code>.Second second = 2;</code>
       */
      public Builder mergeSecond(com.blueapron.connect.protobuf.OneOfStructs.Second value) {
        if (secondBuilder_ == null) {
          if (possibilitiesCase_ == 2 &&
              possibilities_ != com.blueapron.connect.protobuf.OneOfStructs.Second.getDefaultInstance()) {
            possibilities_ = com.blueapron.connect.protobuf.OneOfStructs.Second.newBuilder((com.blueapron.connect.protobuf.OneOfStructs.Second) possibilities_)
                .mergeFrom(value).buildPartial();
          } else {
            possibilities_ = value;
          }
          onChanged();
        } else {
          if (possibilitiesCase_ == 2) {
            secondBuilder_.mergeFrom(value);
          }
          secondBuilder_.setMessage(value);
        }
        possibilitiesCase_ = 2;
        return this;
      }
      /**
       * <code>.Second second = 2;</code>
       */
      public Builder clearSecond() {
        if (secondBuilder_ == null) {
          if (possibilitiesCase_ == 2) {
            possibilitiesCase_ = 0;
            possibilities_ = null;
            onChanged();
          }
        } else {
          if (possibilitiesCase_ == 2) {
            possibilitiesCase_ = 0;
            possibilities_ = null;
          }
          secondBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Second second = 2;</code>
       */
      public com.blueapron.connect.protobuf.OneOfStructs.Second.Builder getSecondBuilder() {
        return getSecondFieldBuilder().getBuilder();
      }
      /**
       * <code>.Second second = 2;</code>
       */
      public com.blueapron.connect.protobuf.OneOfStructs.SecondOrBuilder getSecondOrBuilder() {
        if ((possibilitiesCase_ == 2) && (secondBuilder_ != null)) {
          return secondBuilder_.getMessageOrBuilder();
        } else {
          if (possibilitiesCase_ == 2) {
            return (com.blueapron.connect.protobuf.OneOfStructs.Second) possibilities_;
          }
          return com.blueapron.connect.protobuf.OneOfStructs.Second.getDefaultInstance();
        }
      }
      /**
       * <code>.Second second = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.blueapron.connect.protobuf.OneOfStructs.Second, com.blueapron.connect.protobuf.OneOfStructs.Second.Builder, com.blueapron.connect.protobuf.OneOfStructs.SecondOrBuilder> 
          getSecondFieldBuilder() {
        if (secondBuilder_ == null) {
          if (!(possibilitiesCase_ == 2)) {
            possibilities_ = com.blueapron.connect.protobuf.OneOfStructs.Second.getDefaultInstance();
          }
          secondBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.blueapron.connect.protobuf.OneOfStructs.Second, com.blueapron.connect.protobuf.OneOfStructs.Second.Builder, com.blueapron.connect.protobuf.OneOfStructs.SecondOrBuilder>(
                  (com.blueapron.connect.protobuf.OneOfStructs.Second) possibilities_,
                  getParentForChildren(),
                  isClean());
          possibilities_ = null;
        }
        possibilitiesCase_ = 2;
        onChanged();;
        return secondBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OneOfContainer)
    }

    // @@protoc_insertion_point(class_scope:OneOfContainer)
    private static final com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer();
    }

    public static com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OneOfContainer>
        PARSER = new com.google.protobuf.AbstractParser<OneOfContainer>() {
      @java.lang.Override
      public OneOfContainer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OneOfContainer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OneOfContainer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OneOfContainer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.blueapron.connect.protobuf.OneOfStructs.OneOfContainer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_First_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_First_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Second_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Second_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OneOfContainer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OneOfContainer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022OneOfStructs.proto\"\026\n\005First\022\r\n\005value\030\001" +
      " \001(\t\"\027\n\006Second\022\r\n\005value\030\002 \001(\t\"U\n\016OneOfCo" +
      "ntainer\022\027\n\005first\030\001 \001(\0132\006.FirstH\000\022\031\n\006seco" +
      "nd\030\002 \001(\0132\007.SecondH\000B\017\n\rpossibilitiesB \n\036" +
      "com.blueapron.connect.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_First_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_First_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_First_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_Second_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Second_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Second_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_OneOfContainer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OneOfContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OneOfContainer_descriptor,
        new java.lang.String[] { "First", "Second", "Possibilities", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
