// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DTO.proto

package com.tradeshift.backend.journal;

public final class DTO {
  private DTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UUIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dto.UUID)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required fixed64 least_significant_bits = 1;</code>
     * @return Whether the leastSignificantBits field is set.
     */
    boolean hasLeastSignificantBits();
    /**
     * <code>required fixed64 least_significant_bits = 1;</code>
     * @return The leastSignificantBits.
     */
    long getLeastSignificantBits();

    /**
     * <code>required fixed64 most_significant_bits = 2;</code>
     * @return Whether the mostSignificantBits field is set.
     */
    boolean hasMostSignificantBits();
    /**
     * <code>required fixed64 most_significant_bits = 2;</code>
     * @return The mostSignificantBits.
     */
    long getMostSignificantBits();
  }
  /**
   * <pre>
   **
   * A 128-bit id, transferred as two 64-bit longs
   * </pre>
   *
   * Protobuf type {@code dto.UUID}
   */
  public  static final class UUID extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dto.UUID)
      UUIDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UUID.newBuilder() to construct.
    private UUID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UUID() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UUID();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UUID(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              bitField0_ |= 0x00000001;
              leastSignificantBits_ = input.readFixed64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              mostSignificantBits_ = input.readFixed64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeshift.backend.journal.DTO.internal_static_dto_UUID_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeshift.backend.journal.DTO.internal_static_dto_UUID_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeshift.backend.journal.DTO.UUID.class, com.tradeshift.backend.journal.DTO.UUID.Builder.class);
    }

    private int bitField0_;
    public static final int LEAST_SIGNIFICANT_BITS_FIELD_NUMBER = 1;
    private long leastSignificantBits_;
    /**
     * <code>required fixed64 least_significant_bits = 1;</code>
     * @return Whether the leastSignificantBits field is set.
     */
    public boolean hasLeastSignificantBits() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required fixed64 least_significant_bits = 1;</code>
     * @return The leastSignificantBits.
     */
    public long getLeastSignificantBits() {
      return leastSignificantBits_;
    }

    public static final int MOST_SIGNIFICANT_BITS_FIELD_NUMBER = 2;
    private long mostSignificantBits_;
    /**
     * <code>required fixed64 most_significant_bits = 2;</code>
     * @return Whether the mostSignificantBits field is set.
     */
    public boolean hasMostSignificantBits() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required fixed64 most_significant_bits = 2;</code>
     * @return The mostSignificantBits.
     */
    public long getMostSignificantBits() {
      return mostSignificantBits_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLeastSignificantBits()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMostSignificantBits()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeFixed64(1, leastSignificantBits_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFixed64(2, mostSignificantBits_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, leastSignificantBits_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, mostSignificantBits_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tradeshift.backend.journal.DTO.UUID)) {
        return super.equals(obj);
      }
      com.tradeshift.backend.journal.DTO.UUID other = (com.tradeshift.backend.journal.DTO.UUID) obj;

      if (hasLeastSignificantBits() != other.hasLeastSignificantBits()) return false;
      if (hasLeastSignificantBits()) {
        if (getLeastSignificantBits()
            != other.getLeastSignificantBits()) return false;
      }
      if (hasMostSignificantBits() != other.hasMostSignificantBits()) return false;
      if (hasMostSignificantBits()) {
        if (getMostSignificantBits()
            != other.getMostSignificantBits()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLeastSignificantBits()) {
        hash = (37 * hash) + LEAST_SIGNIFICANT_BITS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLeastSignificantBits());
      }
      if (hasMostSignificantBits()) {
        hash = (37 * hash) + MOST_SIGNIFICANT_BITS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMostSignificantBits());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tradeshift.backend.journal.DTO.UUID parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradeshift.backend.journal.DTO.UUID parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradeshift.backend.journal.DTO.UUID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradeshift.backend.journal.DTO.UUID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradeshift.backend.journal.DTO.UUID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradeshift.backend.journal.DTO.UUID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradeshift.backend.journal.DTO.UUID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tradeshift.backend.journal.DTO.UUID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tradeshift.backend.journal.DTO.UUID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tradeshift.backend.journal.DTO.UUID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tradeshift.backend.journal.DTO.UUID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tradeshift.backend.journal.DTO.UUID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tradeshift.backend.journal.DTO.UUID prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * A 128-bit id, transferred as two 64-bit longs
     * </pre>
     *
     * Protobuf type {@code dto.UUID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dto.UUID)
        com.tradeshift.backend.journal.DTO.UUIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tradeshift.backend.journal.DTO.internal_static_dto_UUID_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tradeshift.backend.journal.DTO.internal_static_dto_UUID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tradeshift.backend.journal.DTO.UUID.class, com.tradeshift.backend.journal.DTO.UUID.Builder.class);
      }

      // Construct using com.tradeshift.backend.journal.DTO.UUID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        leastSignificantBits_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        mostSignificantBits_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tradeshift.backend.journal.DTO.internal_static_dto_UUID_descriptor;
      }

      @java.lang.Override
      public com.tradeshift.backend.journal.DTO.UUID getDefaultInstanceForType() {
        return com.tradeshift.backend.journal.DTO.UUID.getDefaultInstance();
      }

      @java.lang.Override
      public com.tradeshift.backend.journal.DTO.UUID build() {
        com.tradeshift.backend.journal.DTO.UUID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tradeshift.backend.journal.DTO.UUID buildPartial() {
        com.tradeshift.backend.journal.DTO.UUID result = new com.tradeshift.backend.journal.DTO.UUID(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.leastSignificantBits_ = leastSignificantBits_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.mostSignificantBits_ = mostSignificantBits_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tradeshift.backend.journal.DTO.UUID) {
          return mergeFrom((com.tradeshift.backend.journal.DTO.UUID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tradeshift.backend.journal.DTO.UUID other) {
        if (other == com.tradeshift.backend.journal.DTO.UUID.getDefaultInstance()) return this;
        if (other.hasLeastSignificantBits()) {
          setLeastSignificantBits(other.getLeastSignificantBits());
        }
        if (other.hasMostSignificantBits()) {
          setMostSignificantBits(other.getMostSignificantBits());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasLeastSignificantBits()) {
          return false;
        }
        if (!hasMostSignificantBits()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tradeshift.backend.journal.DTO.UUID parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tradeshift.backend.journal.DTO.UUID) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long leastSignificantBits_ ;
      /**
       * <code>required fixed64 least_significant_bits = 1;</code>
       * @return Whether the leastSignificantBits field is set.
       */
      public boolean hasLeastSignificantBits() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required fixed64 least_significant_bits = 1;</code>
       * @return The leastSignificantBits.
       */
      public long getLeastSignificantBits() {
        return leastSignificantBits_;
      }
      /**
       * <code>required fixed64 least_significant_bits = 1;</code>
       * @param value The leastSignificantBits to set.
       * @return This builder for chaining.
       */
      public Builder setLeastSignificantBits(long value) {
        bitField0_ |= 0x00000001;
        leastSignificantBits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 least_significant_bits = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeastSignificantBits() {
        bitField0_ = (bitField0_ & ~0x00000001);
        leastSignificantBits_ = 0L;
        onChanged();
        return this;
      }

      private long mostSignificantBits_ ;
      /**
       * <code>required fixed64 most_significant_bits = 2;</code>
       * @return Whether the mostSignificantBits field is set.
       */
      public boolean hasMostSignificantBits() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required fixed64 most_significant_bits = 2;</code>
       * @return The mostSignificantBits.
       */
      public long getMostSignificantBits() {
        return mostSignificantBits_;
      }
      /**
       * <code>required fixed64 most_significant_bits = 2;</code>
       * @param value The mostSignificantBits to set.
       * @return This builder for chaining.
       */
      public Builder setMostSignificantBits(long value) {
        bitField0_ |= 0x00000002;
        mostSignificantBits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed64 most_significant_bits = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMostSignificantBits() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mostSignificantBits_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dto.UUID)
    }

    // @@protoc_insertion_point(class_scope:dto.UUID)
    private static final com.tradeshift.backend.journal.DTO.UUID DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tradeshift.backend.journal.DTO.UUID();
    }

    public static com.tradeshift.backend.journal.DTO.UUID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UUID>
        PARSER = new com.google.protobuf.AbstractParser<UUID>() {
      @java.lang.Override
      public UUID parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UUID(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UUID> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UUID> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tradeshift.backend.journal.DTO.UUID getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EventEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dto.EventEnvelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
     * document, role, or other, that is affected by the edit.
     * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
     * and that is atomically affected by this event, and not affected until further events arrive.
     * </pre>
     *
     * <code>optional string aggregateId = 1;</code>
     * @return Whether the aggregateId field is set.
     */
    boolean hasAggregateId();
    /**
     * <pre>
     **
     * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
     * document, role, or other, that is affected by the edit.
     * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
     * and that is atomically affected by this event, and not affected until further events arrive.
     * </pre>
     *
     * <code>optional string aggregateId = 1;</code>
     * @return The aggregateId.
     */
    java.lang.String getAggregateId();
    /**
     * <pre>
     **
     * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
     * document, role, or other, that is affected by the edit.
     * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
     * and that is atomically affected by this event, and not affected until further events arrive.
     * </pre>
     *
     * <code>optional string aggregateId = 1;</code>
     * @return The bytes for aggregateId.
     */
    com.google.protobuf.ByteString
        getAggregateIdBytes();

    /**
     * <pre>
     **
     * The sequence number (within the aggregate) of this this event. Event sequence numbers are monotonically
     * increasing per aggregateId. Hence, the combination of (aggregateId, sequenceNr) is unique.
     * </pre>
     *
     * <code>optional uint64 sequenceNr = 2;</code>
     * @return Whether the sequenceNr field is set.
     */
    boolean hasSequenceNr();
    /**
     * <pre>
     **
     * The sequence number (within the aggregate) of this this event. Event sequence numbers are monotonically
     * increasing per aggregateId. Hence, the combination of (aggregateId, sequenceNr) is unique.
     * </pre>
     *
     * <code>optional uint64 sequenceNr = 2;</code>
     * @return The sequenceNr.
     */
    long getSequenceNr();

    /**
     * <pre>
     **
     * The timestamp, in milliseconds since the epoch, when this event was written to the event journal. This
     * is not necessarily the same as the timestamp in which the change inside the event actually took place
     * in the real world; specifically for imported events (that happened before we had an event journal),
     * there may be a big difference.
     * </pre>
     *
     * <code>optional uint64 timestamp = 3;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <pre>
     **
     * The timestamp, in milliseconds since the epoch, when this event was written to the event journal. This
     * is not necessarily the same as the timestamp in which the change inside the event actually took place
     * in the real world; specifically for imported events (that happened before we had an event journal),
     * there may be a big difference.
     * </pre>
     *
     * <code>optional uint64 timestamp = 3;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     **
     * The event content itself, in protobuf format, according to one of the journal-specific event protobuf
     * definitions.
     * </pre>
     *
     * <code>optional bytes event = 4;</code>
     * @return Whether the event field is set.
     */
    boolean hasEvent();
    /**
     * <pre>
     **
     * The event content itself, in protobuf format, according to one of the journal-specific event protobuf
     * definitions.
     * </pre>
     *
     * <code>optional bytes event = 4;</code>
     * @return The event.
     */
    com.google.protobuf.ByteString getEvent();
  }
  /**
   * <pre>
   **
   * Generic wrapper envelope that is returned when querying the event journal.
   * </pre>
   *
   * Protobuf type {@code dto.EventEnvelope}
   */
  public  static final class EventEnvelope extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dto.EventEnvelope)
      EventEnvelopeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventEnvelope.newBuilder() to construct.
    private EventEnvelope(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventEnvelope() {
      aggregateId_ = "";
      event_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventEnvelope();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EventEnvelope(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              aggregateId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sequenceNr_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readUInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              event_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tradeshift.backend.journal.DTO.internal_static_dto_EventEnvelope_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tradeshift.backend.journal.DTO.internal_static_dto_EventEnvelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tradeshift.backend.journal.DTO.EventEnvelope.class, com.tradeshift.backend.journal.DTO.EventEnvelope.Builder.class);
    }

    private int bitField0_;
    public static final int AGGREGATEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object aggregateId_;
    /**
     * <pre>
     **
     * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
     * document, role, or other, that is affected by the edit.
     * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
     * and that is atomically affected by this event, and not affected until further events arrive.
     * </pre>
     *
     * <code>optional string aggregateId = 1;</code>
     * @return Whether the aggregateId field is set.
     */
    public boolean hasAggregateId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     **
     * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
     * document, role, or other, that is affected by the edit.
     * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
     * and that is atomically affected by this event, and not affected until further events arrive.
     * </pre>
     *
     * <code>optional string aggregateId = 1;</code>
     * @return The aggregateId.
     */
    public java.lang.String getAggregateId() {
      java.lang.Object ref = aggregateId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          aggregateId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     **
     * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
     * document, role, or other, that is affected by the edit.
     * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
     * and that is atomically affected by this event, and not affected until further events arrive.
     * </pre>
     *
     * <code>optional string aggregateId = 1;</code>
     * @return The bytes for aggregateId.
     */
    public com.google.protobuf.ByteString
        getAggregateIdBytes() {
      java.lang.Object ref = aggregateId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aggregateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQUENCENR_FIELD_NUMBER = 2;
    private long sequenceNr_;
    /**
     * <pre>
     **
     * The sequence number (within the aggregate) of this this event. Event sequence numbers are monotonically
     * increasing per aggregateId. Hence, the combination of (aggregateId, sequenceNr) is unique.
     * </pre>
     *
     * <code>optional uint64 sequenceNr = 2;</code>
     * @return Whether the sequenceNr field is set.
     */
    public boolean hasSequenceNr() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     **
     * The sequence number (within the aggregate) of this this event. Event sequence numbers are monotonically
     * increasing per aggregateId. Hence, the combination of (aggregateId, sequenceNr) is unique.
     * </pre>
     *
     * <code>optional uint64 sequenceNr = 2;</code>
     * @return The sequenceNr.
     */
    public long getSequenceNr() {
      return sequenceNr_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <pre>
     **
     * The timestamp, in milliseconds since the epoch, when this event was written to the event journal. This
     * is not necessarily the same as the timestamp in which the change inside the event actually took place
     * in the real world; specifically for imported events (that happened before we had an event journal),
     * there may be a big difference.
     * </pre>
     *
     * <code>optional uint64 timestamp = 3;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     **
     * The timestamp, in milliseconds since the epoch, when this event was written to the event journal. This
     * is not necessarily the same as the timestamp in which the change inside the event actually took place
     * in the real world; specifically for imported events (that happened before we had an event journal),
     * there may be a big difference.
     * </pre>
     *
     * <code>optional uint64 timestamp = 3;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int EVENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString event_;
    /**
     * <pre>
     **
     * The event content itself, in protobuf format, according to one of the journal-specific event protobuf
     * definitions.
     * </pre>
     *
     * <code>optional bytes event = 4;</code>
     * @return Whether the event field is set.
     */
    public boolean hasEvent() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     **
     * The event content itself, in protobuf format, according to one of the journal-specific event protobuf
     * definitions.
     * </pre>
     *
     * <code>optional bytes event = 4;</code>
     * @return The event.
     */
    public com.google.protobuf.ByteString getEvent() {
      return event_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aggregateId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt64(2, sequenceNr_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, event_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aggregateId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, sequenceNr_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, event_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tradeshift.backend.journal.DTO.EventEnvelope)) {
        return super.equals(obj);
      }
      com.tradeshift.backend.journal.DTO.EventEnvelope other = (com.tradeshift.backend.journal.DTO.EventEnvelope) obj;

      if (hasAggregateId() != other.hasAggregateId()) return false;
      if (hasAggregateId()) {
        if (!getAggregateId()
            .equals(other.getAggregateId())) return false;
      }
      if (hasSequenceNr() != other.hasSequenceNr()) return false;
      if (hasSequenceNr()) {
        if (getSequenceNr()
            != other.getSequenceNr()) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (hasEvent() != other.hasEvent()) return false;
      if (hasEvent()) {
        if (!getEvent()
            .equals(other.getEvent())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAggregateId()) {
        hash = (37 * hash) + AGGREGATEID_FIELD_NUMBER;
        hash = (53 * hash) + getAggregateId().hashCode();
      }
      if (hasSequenceNr()) {
        hash = (37 * hash) + SEQUENCENR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSequenceNr());
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasEvent()) {
        hash = (37 * hash) + EVENT_FIELD_NUMBER;
        hash = (53 * hash) + getEvent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tradeshift.backend.journal.DTO.EventEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tradeshift.backend.journal.DTO.EventEnvelope prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * Generic wrapper envelope that is returned when querying the event journal.
     * </pre>
     *
     * Protobuf type {@code dto.EventEnvelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dto.EventEnvelope)
        com.tradeshift.backend.journal.DTO.EventEnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tradeshift.backend.journal.DTO.internal_static_dto_EventEnvelope_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tradeshift.backend.journal.DTO.internal_static_dto_EventEnvelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tradeshift.backend.journal.DTO.EventEnvelope.class, com.tradeshift.backend.journal.DTO.EventEnvelope.Builder.class);
      }

      // Construct using com.tradeshift.backend.journal.DTO.EventEnvelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        aggregateId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sequenceNr_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        event_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tradeshift.backend.journal.DTO.internal_static_dto_EventEnvelope_descriptor;
      }

      @java.lang.Override
      public com.tradeshift.backend.journal.DTO.EventEnvelope getDefaultInstanceForType() {
        return com.tradeshift.backend.journal.DTO.EventEnvelope.getDefaultInstance();
      }

      @java.lang.Override
      public com.tradeshift.backend.journal.DTO.EventEnvelope build() {
        com.tradeshift.backend.journal.DTO.EventEnvelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tradeshift.backend.journal.DTO.EventEnvelope buildPartial() {
        com.tradeshift.backend.journal.DTO.EventEnvelope result = new com.tradeshift.backend.journal.DTO.EventEnvelope(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.aggregateId_ = aggregateId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sequenceNr_ = sequenceNr_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.event_ = event_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tradeshift.backend.journal.DTO.EventEnvelope) {
          return mergeFrom((com.tradeshift.backend.journal.DTO.EventEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tradeshift.backend.journal.DTO.EventEnvelope other) {
        if (other == com.tradeshift.backend.journal.DTO.EventEnvelope.getDefaultInstance()) return this;
        if (other.hasAggregateId()) {
          bitField0_ |= 0x00000001;
          aggregateId_ = other.aggregateId_;
          onChanged();
        }
        if (other.hasSequenceNr()) {
          setSequenceNr(other.getSequenceNr());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasEvent()) {
          setEvent(other.getEvent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tradeshift.backend.journal.DTO.EventEnvelope parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tradeshift.backend.journal.DTO.EventEnvelope) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object aggregateId_ = "";
      /**
       * <pre>
       **
       * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
       * document, role, or other, that is affected by the edit.
       * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
       * and that is atomically affected by this event, and not affected until further events arrive.
       * </pre>
       *
       * <code>optional string aggregateId = 1;</code>
       * @return Whether the aggregateId field is set.
       */
      public boolean hasAggregateId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       **
       * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
       * document, role, or other, that is affected by the edit.
       * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
       * and that is atomically affected by this event, and not affected until further events arrive.
       * </pre>
       *
       * <code>optional string aggregateId = 1;</code>
       * @return The aggregateId.
       */
      public java.lang.String getAggregateId() {
        java.lang.Object ref = aggregateId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            aggregateId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
       * document, role, or other, that is affected by the edit.
       * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
       * and that is atomically affected by this event, and not affected until further events arrive.
       * </pre>
       *
       * <code>optional string aggregateId = 1;</code>
       * @return The bytes for aggregateId.
       */
      public com.google.protobuf.ByteString
          getAggregateIdBytes() {
        java.lang.Object ref = aggregateId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          aggregateId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
       * document, role, or other, that is affected by the edit.
       * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
       * and that is atomically affected by this event, and not affected until further events arrive.
       * </pre>
       *
       * <code>optional string aggregateId = 1;</code>
       * @param value The aggregateId to set.
       * @return This builder for chaining.
       */
      public Builder setAggregateId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        aggregateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
       * document, role, or other, that is affected by the edit.
       * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
       * and that is atomically affected by this event, and not affected until further events arrive.
       * </pre>
       *
       * <code>optional string aggregateId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAggregateId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        aggregateId_ = getDefaultInstance().getAggregateId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * The UUID of the aggregate for which an event has been emitted. This is the UUID of the company,
       * document, role, or other, that is affected by the edit.
       * The word "aggregate" stems from Domain-Driven Design: It's the unit of change that the event affects,
       * and that is atomically affected by this event, and not affected until further events arrive.
       * </pre>
       *
       * <code>optional string aggregateId = 1;</code>
       * @param value The bytes for aggregateId to set.
       * @return This builder for chaining.
       */
      public Builder setAggregateIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        aggregateId_ = value;
        onChanged();
        return this;
      }

      private long sequenceNr_ ;
      /**
       * <pre>
       **
       * The sequence number (within the aggregate) of this this event. Event sequence numbers are monotonically
       * increasing per aggregateId. Hence, the combination of (aggregateId, sequenceNr) is unique.
       * </pre>
       *
       * <code>optional uint64 sequenceNr = 2;</code>
       * @return Whether the sequenceNr field is set.
       */
      public boolean hasSequenceNr() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       **
       * The sequence number (within the aggregate) of this this event. Event sequence numbers are monotonically
       * increasing per aggregateId. Hence, the combination of (aggregateId, sequenceNr) is unique.
       * </pre>
       *
       * <code>optional uint64 sequenceNr = 2;</code>
       * @return The sequenceNr.
       */
      public long getSequenceNr() {
        return sequenceNr_;
      }
      /**
       * <pre>
       **
       * The sequence number (within the aggregate) of this this event. Event sequence numbers are monotonically
       * increasing per aggregateId. Hence, the combination of (aggregateId, sequenceNr) is unique.
       * </pre>
       *
       * <code>optional uint64 sequenceNr = 2;</code>
       * @param value The sequenceNr to set.
       * @return This builder for chaining.
       */
      public Builder setSequenceNr(long value) {
        bitField0_ |= 0x00000002;
        sequenceNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * The sequence number (within the aggregate) of this this event. Event sequence numbers are monotonically
       * increasing per aggregateId. Hence, the combination of (aggregateId, sequenceNr) is unique.
       * </pre>
       *
       * <code>optional uint64 sequenceNr = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequenceNr() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sequenceNr_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       **
       * The timestamp, in milliseconds since the epoch, when this event was written to the event journal. This
       * is not necessarily the same as the timestamp in which the change inside the event actually took place
       * in the real world; specifically for imported events (that happened before we had an event journal),
       * there may be a big difference.
       * </pre>
       *
       * <code>optional uint64 timestamp = 3;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       **
       * The timestamp, in milliseconds since the epoch, when this event was written to the event journal. This
       * is not necessarily the same as the timestamp in which the change inside the event actually took place
       * in the real world; specifically for imported events (that happened before we had an event journal),
       * there may be a big difference.
       * </pre>
       *
       * <code>optional uint64 timestamp = 3;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       **
       * The timestamp, in milliseconds since the epoch, when this event was written to the event journal. This
       * is not necessarily the same as the timestamp in which the change inside the event actually took place
       * in the real world; specifically for imported events (that happened before we had an event journal),
       * there may be a big difference.
       * </pre>
       *
       * <code>optional uint64 timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * The timestamp, in milliseconds since the epoch, when this event was written to the event journal. This
       * is not necessarily the same as the timestamp in which the change inside the event actually took place
       * in the real world; specifically for imported events (that happened before we had an event journal),
       * there may be a big difference.
       * </pre>
       *
       * <code>optional uint64 timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString event_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       **
       * The event content itself, in protobuf format, according to one of the journal-specific event protobuf
       * definitions.
       * </pre>
       *
       * <code>optional bytes event = 4;</code>
       * @return Whether the event field is set.
       */
      public boolean hasEvent() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       **
       * The event content itself, in protobuf format, according to one of the journal-specific event protobuf
       * definitions.
       * </pre>
       *
       * <code>optional bytes event = 4;</code>
       * @return The event.
       */
      public com.google.protobuf.ByteString getEvent() {
        return event_;
      }
      /**
       * <pre>
       **
       * The event content itself, in protobuf format, according to one of the journal-specific event protobuf
       * definitions.
       * </pre>
       *
       * <code>optional bytes event = 4;</code>
       * @param value The event to set.
       * @return This builder for chaining.
       */
      public Builder setEvent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * The event content itself, in protobuf format, according to one of the journal-specific event protobuf
       * definitions.
       * </pre>
       *
       * <code>optional bytes event = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEvent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        event_ = getDefaultInstance().getEvent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dto.EventEnvelope)
    }

    // @@protoc_insertion_point(class_scope:dto.EventEnvelope)
    private static final com.tradeshift.backend.journal.DTO.EventEnvelope DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tradeshift.backend.journal.DTO.EventEnvelope();
    }

    public static com.tradeshift.backend.journal.DTO.EventEnvelope getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EventEnvelope>
        PARSER = new com.google.protobuf.AbstractParser<EventEnvelope>() {
      @java.lang.Override
      public EventEnvelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventEnvelope(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventEnvelope> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventEnvelope> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tradeshift.backend.journal.DTO.EventEnvelope getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dto_UUID_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dto_UUID_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dto_EventEnvelope_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dto_EventEnvelope_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tDTO.proto\022\003dto\"E\n\004UUID\022\036\n\026least_signif" +
      "icant_bits\030\001 \002(\006\022\035\n\025most_significant_bit" +
      "s\030\002 \002(\006\"Z\n\rEventEnvelope\022\023\n\013aggregateId\030" +
      "\001 \001(\t\022\022\n\nsequenceNr\030\002 \001(\004\022\021\n\ttimestamp\030\003" +
      " \001(\004\022\r\n\005event\030\004 \001(\014B \n\036com.tradeshift.ba" +
      "ckend.journal"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dto_UUID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dto_UUID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dto_UUID_descriptor,
        new java.lang.String[] { "LeastSignificantBits", "MostSignificantBits", });
    internal_static_dto_EventEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dto_EventEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dto_EventEnvelope_descriptor,
        new java.lang.String[] { "AggregateId", "SequenceNr", "Timestamp", "Event", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
