name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up commit signing w/ GPG
        id: gpg
        run: |
          KEYDIR=$(mktemp -d)
          KEYFILE="${KEYDIR}/key.asc"
          echo "$GPG_KEY" > "${KEYFILE}"
          GPG_SHORTID=$(gpg --show-keys --keyid-format=long "${KEYFILE}" | grep sec | cut -d/ -f2 | cut -d' ' -f1)
          gpg --import --batch --yes "${KEYFILE}"
          git config --global commit.gpgsign true
          git config --global user.signingkey "${GPG_SHORTID}"
          # Get the "This User <this@email.com>" of the key:
          GPG_USER=$(gpg --fingerprint "${GPG_SHORTID}" | sed -n '/^uid/s/.*\]\s//p')
          echo "::set-output name=user::${GPG_USER}"
        env:
          GPG_KEY: ${{ secrets.gpg-key }}

      - name: Run Maven
        run: mvn -B verify

